title: Epicevent’s Math Blog
description: 수학 시리즈 블로그입니다.

#theme: no-style-please
remote_theme: riggraz/no-style-please
# 포스트 주소 형식 설정
permalink: /:categories/:slug.html
favicon: "logo.png"
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    disable : true

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]


# (선택) collections 항목 제거 또는 빈 객체로 설정
collections: {}
theme_config:
  back_home_text: "홈으로"
  # light, dark, auto 중 선택 가능
  appearance: auto
